add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_commit$git_state$git_status]($style)$character"

[character]
error_symbol = "[âœ—](bold cyan)"
success_symbol = "[â¯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "â€¦/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_commit]
format = '[\($hash$tag\)]($style) '
style = "cyan"
only_detached = true
tag_disabled = false
tag_symbol = " "

[git_state]
format = '[\[$state( $progress_current/$progress_total)\]]($style) '
style = "bright-black"

[git_status]
format     = '[$all_status$ahead_behind]($style)'
style      = "cyan"
ahead      = "â‡¡${count} "
diverged   = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind     = "â‡£${count} "
conflicted = "î®« "
up_to_date = "ï€Œ "
untracked  = "? "
modified   = "î©± "
stashed    = "ğŸ“¦ "
staged     = ""
renamed    = "Â» "
deleted    = ""
